[package]
name = "basmap"
version = "0.6.0"
authors = ["Andrew Buntine Of Doom <info@bunts.io>"]

#[lib]
#name = "basmap"
#path = "src/basmap.rs"

[dependencies]
getopts = "0.2"
hyper = "0.6"
xml-rs = "0.2"
ansi_term = "*"
flate2 = "0.2"
